### ISSUE TITLE
Remove Appveyor

### ISSUE THREAD

**Issue by kotp** [exercism/delphi#125]
We aren't using Appveyor at the moment, and it is failing, so should be removed.

**Comment by rpottsoh** [comment]
Appveyor appears to be active again.  Just submitted #132.

**Comment by kotp** [comment]
I removed the `xdelphi` project from the listing in my appveyor account, but upon the check (PR #133) it made it worse. 

Can you check if the project is listed for you there?

**Comment by rpottsoh** [comment]
@kotp I logged into my Appveyor account, it has no projects or environments listed.  It looks like a clean slate.

**Comment by rpottsoh** [comment]
@kotp I have revoked OAuth access to Appveyor to my account...  That hasn't had any effect.  Not sure what else I can do...

**Comment by rpottsoh** [comment]
I think @kytrinyx has this issue resolved.
