### ISSUE TITLE
Broken links in ALL exercise READMEs

### ISSUE THREAD

**Issue by rpottsoh** [exercism/delphi#243]
@kytrinyx  or @iHiD all exercise READMEs for this track point to https://www.exercism.io/languages/delphi/installation.  This link is currently not working.  I need to know what the new link is or how I should go about correcting this issue.

**Comment by kytrinyx** [comment]
This is a problem on our end. These should be redirecting, but are not.

You can fix it by replacing them with https://exercism.io/tracks/delphi/installation.

**Comment by iHiD** [comment]
Can I close this in favour of #3861 pls?

**Comment by rpottsoh** [comment]
If it covers this issue, of course. 😄

**Comment by rpottsoh** [comment]
I am reopening this issue as the images are still not appearing correctly, appearing as broken links.

**Comment by iHiD** [comment]
These images are differnet. They're pointing to `x.exercism.io`. What is that?

**Comment by rpottsoh** [comment]
I honestly couldn't tell you.  The url worked with v1.  Just need to know how to correctly map images in the repo to the site.

Sent from my android device.

**Comment by iHiD** [comment]
@kytrinyx Can you shed any light on where the image at `https://x.exercism.io/v3/tracks/delphi/docs/img/01delphiclicktools.png` would have been in v1 be pls?

**Comment by rpottsoh** [comment]
I attempted, unsuccessfully with #259, to correct the broken links to the images.  I followed the instructions at the bottom of https://github.com/exercism/docs/blob/master/language-tracks/documentation/for-consumers.md

**Comment by rpottsoh** [comment]
Ok, thanks for the feedback.

**Comment by kytrinyx** [comment]
These images are all in https://github.com/exercism/delphi/tree/master/docs/img

**Comment by iHiD** [comment]
Brilliant. Thanks @kytrinyx 

So they need to go to `https://raw.githubusercontent.com/exercism/delphi/master/docs/img/00delphiwelcomepage.png` pls, @rpottsoh.

And eventually we'll CDN them up for you.

**Comment by rpottsoh** [comment]
Thanks @iHiD.  Simple enough.

**Comment by rpottsoh** [comment]
I have implemented the change in #260 and the images now appear correctly on the site.  Thanks again for the help.  I am going to go ahead and close this.
