### ISSUE TITLE
matrix: add new exercise

### ISSUE THREAD

**Issue by rpottsoh** [exercism/delphi#281]
@filiptoskovic I have made some changes to what you have done, see my commits comments.  Nice work!  I think we should update config.json and then generate the README once robot-simulator has been merged.

**Comment by filiptoskovic** [comment]
Thank you. I really don't know how use git properly. I will read some guide asap. In meanwhile I have finished Pascals triangle. My plan is to add `ocr numbers` next. Sorry for my silly question, but how to update config.json and readme?

**Comment by rpottsoh** [comment]
I'll get back to you on your question regarding config.json and readme.  For git I recommend installing gitkraken.  It is very intuitive and doesn't do any weird monkey business behind the scenes.  It is very much operating like the git CLI without having to know all of  the commands.  Gitkraken is a gui.

Are you familiar with gitter?   It would be a better way to communicate instead of in an issue.



Sent from my android device.

**Comment by filiptoskovic** [comment]
Sorry but no, I'm not familiar with anything that starts with git, but I read fast. Will download Gitkraken, and I think I'm joined exercism/Pascal-Delphi room on Gitter.

**Comment by rpottsoh** [comment]
I have rebased branch matrix on to master.  It is OK to finish adding exercise matrix.  If you want to create a PR that is fine.  config.json needs to be updated and a README generated.

The config.json entry will look like this:
```
    {
      "slug": "matrix",
      "uuid": "c1c01b18-7473-47fc-a86f-a770b844435b",
      "core": false,
      "unlocked_by": "grade-school",
      "difficulty": 4,
      "topics": [
        "matrices",
        "parsing"
      ]
    },
```

This should be inserted after `acronym`.

Once config.json is update the app `configlet` can be utilized to generate the README.  You can find the configlet here: https://github.com/exercism/configlet/releases
It is a CLI tool used to help maintain the language tracks.

**Comment by filiptoskovic** [comment]
I'm really sorry, but this Git stuff don't like me. Can you take a look when you have a time. I have added readme and updated config, and accidentally added pascal triangle... It must be that some of basic concepts I have misunderstood.

**Comment by rpottsoh** [comment]
I will take a look.  The Gitkraken site has many video tutorials on
how to navigate github (or git in general) using their gui client.  A
good way to practice the skills taught is to create a repo of your own
and to practice the various things the videos teach.  At any time you
can then delete the repo since you are only using for learning anyway.

I am not very good with the CLI git client.  I know people that are
good with it.  If you have questions specific to how to do something
using gitkraken I can help you out.

**Comment by rpottsoh** [comment]
@filiptoskovic your fork is all happy again.  I know the pain you are feeling, I was there about two years ago.  The `matrix` branch is ready for config.json to be updated as I indicated in my comment earlier (above).  After that the README can be generated.  The PR can be opened at anytime.

**Comment by rpottsoh** [comment]
Thanks for working on this @filiptoskovic .  You should delete the `matrix` branch from your fork since it has been merged.  You also need to pull from remote/master to local/master and then push from local master to origin/master (this will update local and origin master to be in sync with remote master).  Remember the repo exists in three places.  As an Exercism repo (remote), as a fork, that you own (origin), and finally locally on your PC (local).  When you create a branch off of local/master it exists as local/{branch name}.  As you commit changes they are added to the local branch.  At some point you should push your changes to origin.  This will create (or update) the branch on your copy of the repo on GitHub (origin).  When you are ready you then create a PR from your branch to remote/master.  Remember, for what you are working on right now and trying to learn, there is no merging.

Git won't allow you to do things that you are not allowed to do.  However, that doesn't mean it will keep you from doing things you shouldn't do.  :smile:

**Comment by rpottsoh** [comment]
I have opened a private gitter session.
