### ISSUE TITLE
Rewrite incomplete solutions statement

### ISSUE THREAD

**Issue by rpottsoh** [exercism/delphi#401]
The discussion in exercism/exercism#4076 has decided that the incomplete solutions blurb at the end of [exercise_readme.go.tmpl](https://github.com/exercism/delphi/blob/master/config/exercise_readme.go.tmpl) should be worded `It's possible to submit an incomplete solution so you may request help from a mentor.`

To Do:  Open a PR in this repo and make the necessary change to `exercise_readme.go.tmpl`.  The PR should also close this PR by including the phrase `resolves #401` on a line by itself in the first comment.

**Comment by neoprez** [comment]
I'll take care of this for you

**Comment by rpottsoh** [comment]
Hey, thanks.  If you are looking for Hacktoberfest credit wait till next month.

**Comment by neoprez** [comment]
yes, I'll wait

**Comment by Erfaniaa** [comment]
Please review my pull request.
