### ISSUE TITLE
Check docs are up to date

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/delphi#467]
Please check if your documentation files are still up-to-date.

The key documentation files to check are:

- `docs/ABOUT.md`
- `docs/INSTALLATION.md`
- `docs/LEARNING.md`
- `docs/RESOURCES.md`
- `docs/TESTS.md`
- `exercises/shared/.docs/help.md`
- `exercises/shared/.docs/tests.md`

There might be more.

## Link check report

To help identify invalid links, we've automatically checked the links of _all_ `*.md` files in this repo.
This is the report of that check:

<pre style="color:#bbb;white-space:pre-wrap;word-wrap:break-word;overflow-wrap:break-word">📝 Summary
---------------------
🔍 Total...........77
✅ Successful......74
⏳ Timeouts.........2
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors...........1

Errors in ./exercises/practice/hello-world/GETTING_STARTED_GUIDE.md
<span style="color:#ffff55">⧖ http://edn.embarcadero.com/article/10280</span>
<span style="color:#ff5555">✗ http://www.sun.com/workshop/java/wp-coding (HTTP status client error (400 Bad Request) for url (http://www.sun.com/workshop/java/wp-coding))</span>

Errors in ./docs/ABOUT.md
<span style="color:#ffff55">⧖ https://edn.embarcadero.com/article/20396</span>

</pre>
## Tracking

https://github.com/exercism/v3-launch/issues/54

**Comment by rpottsoh** [comment]
@ErikSchierboom I am looking into the issues reported.  Only one link appears to be in error and I am removing that one from GETTING_STARTED_GUIDE.md.  The two flagged as Timeouts do actually work, but took a little longer to load, I have no control over that.  Do all the links need to be green?

**Comment by ErikSchierboom** [comment]
@rpottsoh Not at all. What you've done is great.
