### ISSUE TITLE
Old URL used in help.md file

### ISSUE THREAD

**Issue by kotp** [exercism/delphi#479]
As reported on Gitter by a student going through the Delphi track:

> The link supplied in the HELP.md file is not working
> (http://www.exercism.io/languages/delphi/installation) - 404 Error is
> raised

The file that needs updating is the `./exercises/shared/.docs/help.md`
file.

The URL should be _.org_ rather than _.io_.

**Comment by NobbZ** [comment]
It is not only the TLD that changed, if it was then there would be a redirect to the correct ressource.

Correct link would be https://exercism.org/docs/tracks/delphi/installation

So where it used to be `/languages/$track/$topic` before, it is now `/docs/tracks/$track/$topic`.

**Comment by kotp** [comment]
Thanks @NobbZ !
